---
    #
    # Playbook to install the ELK stack + Beats
    #
    - hosts: elk
      remote_user: user 
      become: yes
      become_user: root
      roles:
      - { role: java }
      - { role: elasticsearch }


